[package]
name = "static-reflect"
version = "0.2.0-alpha.2"
edition = "2018"
description = "Static type information, giving a form of compile-time reflection"
license = "MIT"
repository = "https://github.com/DuckLogic/rust-static-reflect"
readme = "README.md"

[dependencies]
educe = "0.4"
# Optional: Support for serde
serde = { version = "1", optional = true, features = ["derive"] }

[dependencies.zerogc]
version = "0.2.0-alpha.5"
git = "https://github.com/DuckLogic/zerogc.git"
branch = "master"
features = ["epsilon"]

[dependencies.zerogc-derive]
version = "0.2.0-alpha.5"
git = "https://github.com/DuckLogic/zerogc.git"
branch = "master"

[features]
default = ["never", "builtins"]
# Support using the never type
never = []
# Support the 'builtin' alternative to stdlib types
builtins = []
serde1 = ["serde", "zerogc/serde1"]


[workspace]
members = ["lib/*"]

[package.metadata.docs.rs]
all-features = true

